#!/usr/bin/env python3

import csv
import io
import json
import os

import requests

HERE = os.path.abspath(os.path.dirname(__file__))
ROOT = os.path.dirname(HERE)
PUBLIC = os.path.join(ROOT, "public")
METADATA_NAME = "metadata.json"
THUMBNAIL_PREFIX = "https://drive.google.com/thumbnail?id="
IMAGE_PREFIX = "https://drive.google.com/uc?export=view&id="


def find_page_url(name):
    name = name.upper()
    path = os.path.join(ROOT, ".env.local")
    with open(path) as f:
        lines = [line.strip() for line in f if line.startswith(f"{name}_PAGE_URL")]
    return lines[-1].split("=", 1)[-1].strip().strip('"')


def download_page(download_dir, page_name):
    path = os.path.join(download_dir, f"{page_name}.md")
    page_url = find_page_url(page_name)
    text = requests.get(page_url).text
    with open(path, "w") as f:
        f.write(text)

    return path


def download_pages(parent_dir):
    pages = ["about"]
    for page in pages:
        download_page(parent_dir, page)


if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser()
    parser.add_argument("-d", "--download-dir", default="production")

    args = parser.parse_args()
    download_pages(args.download_dir)
