#!/usr/bin/env python3

import requests
import yaml


def fetch_access_emails(url):
    emails = requests.get(url).text.splitlines()
    return emails


def replace_access_list(config_file, emails):
    with open(config_file) as f:
        data = yaml.load(f, Loader=yaml.FullLoader)

    data["vouch"]["whiteList"] = emails

    with open(config_file, "w") as g:
        data = yaml.dump(data, g)


if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser()
    parser.add_argument("config_file")
    parser.add_argument("metadata_url")
    args = parser.parse_args()

    emails = fetch_access_emails(args.metadata_url)
    replace_access_list(args.config_file, emails)
